version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_nuvolo
    environment:
      POSTGRES_DB: nuvolo_db
      POSTGRES_USER: nuvolo_user
      POSTGRES_PASSWORD: nuvolo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_nuvolo
    environment:
      REDIS_PASSWORD: nuvolo_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network

volumes:
  postgres_data:
  redis_data:

networks:
  redis_network:
    driver: bridge
