version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_nuvolo
    environment:
      POSTGRES_DB: nuvolo_db
      POSTGRES_USER: nuvolo_user
      POSTGRES_PASSWORD: nuvolo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_nuvolo
    environment:
      REDIS_PASSWORD: nuvolo_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network

  rabbitmq:
    image: rabbitmq:3.13.2-management
    container_name: rabbitmq_nuvolo
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    environment:
      RABBITMQ_DEFAULT_USER: nuvolo
      RABBITMQ_DEFAULT_PASS: nuvolo
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
      restart: unless-stopped
    networks:
      - rabbitmq_network

  minio:
    image: minio/minio
    container_name: minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=nuvolo_minio
      - MINIO_ROOT_PASSWORD=nuvolo_minio

volumes:
  postgres_data:
  redis_data:
  minio_data:
    driver: local

networks:
  redis_network:
    driver: bridge
  rabbitmq_network:
    driver: bridge
  minionetwork:
    driver: bridge
